version: '3.7'

services:
  api:
    image: 'node:12-alpine'
    volumes:
      - './:/shared_dir:cached'
    working_dir: '/shared_dir'
    environment:
      HOST: '0.0.0.0'
    ports:
      - '3000:3000'
    command: >
      sh -c '
        npm install
        npm run dev:watch
      '
