version: '3.7'

services:
  app:
    image: 'node:12-alpine'
    volumes:
      - './:/shared_dir:cached'
    working_dir: '/shared_dir'
    environment:
      HOST: '0.0.0.0'
    ports:
      - '3000:3000'
    command: >
      sh -c '
        npm install
        npm run dev:watch
      '
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      DATABASE_HOST: localhost
    user: root
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
volumes:
  dbdata:
